project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - chapters/SuperchargeWithPythonR.qmd
    - chapters/SuperchargeWithPythonR-before-we-start.qmd
    - chapters/DebitDatabase.qmd
    - chapters/DebitDatabase-before-we-start.qmd
    - chapters/ElevateAccountingWithAnalytics-R.qmd
    - chapters/ElevateAccountingWithAnalytics-R-before-we-start.qmd
    - chapters/ExcelPython.qmd
    - chapters/ExcelPython-before-we-start.qmd
    - chapters/ExcelAccountingwithR.qmd
    - chapters/ExcelAccountingwithR-before-we-start.qmd
    - chapters/ExcelerateAccounting.qmd
    - chapters/ExcelerateAccounting-before-we-start.qmd
    - chapters/InfusePythontoAccounting.qmd
    - chapters/InfusePythontoAccounting-before-we-start.qmd
    - chapters/GAAPforDataVisualization.qmd
    - chapters/PBI_FinancialStatements.qmd
    - chapters/PBI_ForAccountantSeries-before-we-start.qmd
    - chapters/PBI_ForAccountantSeries.qmd
    - chapters/PBI_ManageBudget.qmd
    - chapters/Setup-anacondacode.qmd
    - chapters/Setup-pbidesktop.qmd
    - chapters/Setup-postgreSQL.qmd
    - chapters/Setup-python.qmd
    - chapters/Setup-quarto.qmd
    - chapters/Setup-R.qmd
    - chapters/Setup-positron.qmd

author: Jianyuan(Andy) Hu

website:
  title: "Data Analytics For Accounting Folks"
  
  page-footer: 
    left: Created by Jianyuan(Andy) Hu, 2025 
    right: |
     This webpage was built with <a href="https://quarto.org/">Quarto</a>.
  repo-branch: main
  # page-navigation: true

  sidebar:
    collapse-level: 3
    style: "floating"
    search: false
    # background: "none"
    tools:
    - icon: linkedin
      href: http://linkedin.com/in/andyhu1
    - icon: github
      href: https://github.com/jy-andy-hu
    - icon: person-square
      href: https://jy-andy-hu.github.io/AllAboutMe/
    
    contents:
      - text: "Preface: From One Accountant to Another"
        href: index.qmd

      - section: "Zero to Pro Bootcamps"
        contents:
        - section: "Supercharge Accountants with Analytics"
          contents: 
          - text: "Overview"
            href: chapters/SuperchargeWithPythonR.qmd
          - text: "To Do, Before We Start"
            href: chapters/SuperchargeWithPythonR-before-we-start.qmd
        
        - section: "Power BI Works for Power Accountants"
          contents: 
          - text: "Overview"
            href: chapters/PBI_ForAccountantSeries.qmd
          - text: "To Do, Before We Start"
            href: chapters/PBI_ForAccountantSeries-before-we-start.qmd
        

      - section: "In-Depth Topics"
        contents:
        - section: '1. Modern "Excel-erated" Accounting'
          contents: 
          - text: "Overview"
            href: chapters/ExcelerateAccounting.qmd
          - text: "To Do, Before We Start"
            href: chapters/ExcelerateAccounting-before-we-start.qmd
        - section: "2. Excel Accounting with R"
          contents: 
          - text: "Overview"
            href: chapters/ExcelAccountingwithR.qmd
          - text: "To Do, Before We Start"
            href: chapters/ExcelAccountingwithR-before-we-start.qmd
        - section: "3. Elevate Accounting with Analytics in R"
          contents: 
          - text: "Overview"
            href: chapters/ElevateAccountingWithAnalytics-R.qmd
          - text: "To Do, Before We Start"
            href: chapters/ElevateAccountingWithAnalytics-R-before-we-start.qmd
        - section: "4. Excel and Python: A Tale of Two Power Tools"
          contents:
          - text: "Overview"
            href: chapters/ExcelPython.qmd
          - text: "To Do, Before We Start"
            href: chapters/ExcelPython-before-we-start.qmd
        - section: "5. Infuse Python to Accounting"
          contents:
          - text: "Overview"
            href: chapters/InfusePythontoAccounting.qmd
          - text: "To Do, Before We Start"
            href: chapters/InfusePythontoAccounting-before-we-start.qmd
        - section: '6. "GAAP" for Data Visualization'
          contents:
          - text: "Overview"
            href: chapters/GAAPforDataVisualization.qmd
          - text: "To Do, Before We Start"
            href: chapters/ElevateAccountingWithAnalytics-R-before-we-start.qmd
        - section: "7. Debit Databases, Credit Analytics"
          contents:
          - text: "Overview"
            href: chapters/DebitDatabase.qmd
          - text: "To Do, Before We Start"
            href: chapters/DebitDatabase-before-we-start.qmd
        - section: "8. Power BI for Accountants 1: Engaging Custom Financial Statements"
          contents:
          - text: "Overview"
            href: chapters/PBI_FinancialStatements.qmd
          - text: "To Do, Before We Start"
            href: chapters/PBI_ForAccountantSeries-before-we-start.qmd
        - section: "9. Power BI for Accountants 2: Managing Budget"
          contents:
          - text: "Overview"
            href: chapters/PBI_ManageBudget.qmd  
          - text: "To Do, Before We Start"
            href: chapters/PBI_ForAccountantSeries-before-we-start.qmd        
        - section: "10. Modern Data Platform"
          contents:
          - text: "Overview"
            href: chapters/ModernDataPlatform.qmd


      - section: "Detailed Setup Guides"
        contents: 
          - text: "Get Started with R"
            href: chapters/Setup-R.qmd
          - text: "Get Started with Python"
            href: chapters/Setup-python.qmd
          - text: "Get Started with Positron"
            href: chapters/Setup-positron.qmd
          - text: "Get Started with Quarto"
            href: chapters/Setup-quarto.qmd
          - text: "Get Started with Anaconda Toolbox"
            href: chapters/Setup-anacondacode.qmd
          - text: "Get Started with PostgresSQL"
            href: chapters/Setup-postgreSQL.qmd
          - text: "Get Started with Power BI Desktop"
            href: chapters/Setup-pbidesktop.qmd

format:
  html:
    theme:
      - cerulean
      - custom.scss
    toc: true
    grid:
      sidebar-width: 320px
      body-width: 800px
      margin-width: 200px